# Generated by Django 4.2.5 on 2023-10-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=5)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
    ]
